version: "3"
services:
  prometheus:
    image: $PROMETHEUS_IMAGE
    restart: unless-stopped
    user: root
    hostname: "prometheus"
    volumes:
      - ${PROMETHEUS_CONFIGS_FOLDER}/prometheus.yml:/etc/prometheus/prometheus.yml
      - ${PROMETHEUS_DATA_FOLDER}:/prometheus
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:8.5.13
    restart: unless-stopped
    volumes:
      - $GRAFANA_DATA:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=$GRAFANA_USER
      - GF_SECURITY_ADMIN_PASSWORD=$GRAFANA_PASS
    depends_on:
      - prometheus
    ports:
      - 3000:3000
