version: "3"
services:
  fluentd:
    image: $FLUENTD_IMAGE
    restart: unless-stopped
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    image: $ELASTIC_IMAGE
    restart: unless-stopped
    environment:
      - ELASTIC_CLUSTER=false
      - CLUSTER_NODE_MASTER=true
      - CLUSTER_MASTER_NODE_NAME=es01
      - discovery.type=single-node
    user: root
    expose:
      - 9200
    ports:
      - "9200:9200"
    volumes:
      - $ELASTIC_DATA:/usr/share/elasticsearch/data
    depends_on:
      - fluentd

  kibana:
    image: $KIBANA_IMAGE
    restart: unless-stopped
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
