---
global:
  scrape_interval: '5s'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
        - '51.250.67.187:9090'

  - job_name: 'crawler'
    static_configs:
      - targets:
        - '51.250.67.187:80'

  - job_name: 'ui'
    static_configs:
      - targets:
        - '51.250.67.187:80'

