FROM python:3.6-alpine

ENV FLASK_APP ui.py

COPY . /app
WORKDIR /app

RUN pip install --upgrade pip && \
    cd  search_engine_ui && ls -l && \
    pip install -r requirements.txt -r requirements-test.txt

EXPOSE 8000

ENTRYPOINT [ "/bin/sh", "search_engine_ui/tests/test.sh" ]
