version: '3.3'
services:
  web:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: 'gitlab.example.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://51.250.94.205'
    ports:
      - '80:80'
      - '443:443'
      - '2222:22'
    volumes:
      - '/docker_sys/gitlab/config:/etc/gitlab'
      - '/docker_sys/gitlab/logs:/var/log/gitlab'
      - '/docker_sys/gitlab/data:/var/opt/gitlab'
